main:
	gcc -Wall -c main.c
	gcc -Wall -o main main.o
	rm -R *.o
	./main "/home/sk/Downloads" "<" "2018-03-25 18:00:00"
	./main "/home/sk/Downloads" ">" "2018-03-25 18:00:00"
	./main "/home/sk/Downloads" "=" "2018-03-23 11:29:49"
clean:
	rm -R *.o main